version: "1.0"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: "ai-feed"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ai-feed:
    build: .
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always